# Generated by Django 4.0 on 2022-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_blog_status_alter_my_certification_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_other_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, null=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_percentage', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='my_skills',
            new_name='my_code_skills',
        ),
    ]
