# Generated by Django 4.0 on 2022-01-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_my_other_skills_rename_my_skills_my_code_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publish_time',
            new_name='blog_date',
        ),
    ]
