# Generated by Django 4.0 on 2022-01-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_publish_time_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
